In [1]:
import pandas as pd

syn = pd.read_csv('/home/work/skku/hyo/omop-mapper/data/CONCEPT_SYNONYM.csv', sep='\t')
syn.head()

,concept_id,concept_synonym_name,language_concept_id
0,3019950,CELL MARKERS; Immune globulin A; Immunoglobuli...,4180186
1,3019950,Lymphs IgA/lymph NFr Spec,4180186
2,3019951,Finding; Findings; nursing; Ordinal; Point in ...,4180186
3,3019955,pCO2 Bld Postductal TcCo2,4180186
4,3019955,Bld Postductal; Bld.foot; BldA.foot; Blood; Ca...,4180186

In [2]:
concept = pd.read_csv('/home/work/skku/hyo/omop-mapper/data/CONCEPT.csv', sep='\t')
concept.head()

/tmp/ipykernel_1050536/1353796791.py:1: DtypeWarning: Columns (5,6,9) have mixed types. Specify dtype option on import or set low_memory=False.
  concept = pd.read_csv('/home/work/skku/hyo/omop-mapper/data/CONCEPT.csv', sep='\t')

,concept_id,concept_name,domain_id,vocabulary_id,concept_class_id,standard_concept,concept_code,valid_start_date,valid_end_date,invalid_reason
0,45756805,Pediatric Cardiology,Provider,ABMS,Physician Specialty,S,OMOP4821938,19700101,20991231,NaN
1,45756804,Pediatric Anesthesiology,Provider,ABMS,Physician Specialty,S,OMOP4821939,19700101,20991231,NaN
2,45756803,Pathology-Anatomic / Pathology-Clinical,Provider,ABMS,Physician Specialty,S,OMOP4821940,19700101,20991231,NaN
3,45756802,Pathology - Pediatric,Provider,ABMS,Physician Specialty,S,OMOP4821941,19700101,20991231,NaN
4,45756801,Pathology - Molecular Genetic,Provider,ABMS,Physician Specialty,S,OMOP4821942,19700101,20991231,NaN

In [3]:
syn[syn['language_concept_id'] == 4180186]

,concept_id,concept_synonym_name,language_concept_id
0,3019950,CELL MARKERS; Immune globulin A; Immunoglobuli...,4180186
1,3019950,Lymphs IgA/lymph NFr Spec,4180186
2,3019951,Finding; Findings; nursing; Ordinal; Point in ...,4180186
3,3019955,pCO2 Bld Postductal TcCo2,4180186
4,3019955,Bld Postductal; Bld.foot; BldA.foot; Blood; Ca...,4180186
...,...,...,...
5153378,3019924,E chaffeensis Ab Ser-aCnc,4180186
5153380,3019929,Androsterone 24h Ur-sRate,4180186
5153381,3019929,1 day; 24 hours; 24HR; Androster; Chemistry; Q...,4180186
5153383,3019939,Arm; c; Contr; Contra; Contrst; Document; Elbo...,4180186
5153384,3019939,MR Elbow-L WO+W contr IV,4180186

In [4]:
syn = syn[syn['language_concept_id'].isin([4180186, 4175771])]
syn

,concept_id,concept_synonym_name,language_concept_id
0,3019950,CELL MARKERS; Immune globulin A; Immunoglobuli...,4180186
1,3019950,Lymphs IgA/lymph NFr Spec,4180186
2,3019951,Finding; Findings; nursing; Ordinal; Point in ...,4180186
3,3019955,pCO2 Bld Postductal TcCo2,4180186
4,3019955,Bld Postductal; Bld.foot; BldA.foot; Blood; Ca...,4180186
...,...,...,...
5153378,3019924,E chaffeensis Ab Ser-aCnc,4180186
5153380,3019929,Androsterone 24h Ur-sRate,4180186
5153381,3019929,1 day; 24 hours; 24HR; Androster; Chemistry; Q...,4180186
5153383,3019939,Arm; c; Contr; Contra; Contrst; Document; Elbo...,4180186
5153384,3019939,MR Elbow-L WO+W contr IV,4180186

In [5]:
syn.to_csv('/home/work/skku/hyo/omop-mapper/data/CONCEPT_SYNONYM.csv', sep='\t', index=False)